### ISSUE TITLE
Conditions?

### ISSUE THREAD

**Issue by Chaphasilor** [justintaddei/vue-haptic#1]
Hey,

first off, I love this directive! Super useful and flexible!  
Now, speaking of flexible, I have a use case where I want to have different vibration patterns based on a variable.

To be specific:
I have an element that I can 'disable', and I want an 'error'/'disabled'-vibration only if the variable `isDisabled` is true, else I want the default vibration.

What I would love to be able to do:

```vue
<CustomElement
  v-haptic-condition="isDisabled" v-haptic-true="error" v-haptic-false="default"
>
```
(The syntax was just off of the top of my head, don't mind it too much)

I know it *could* be done with a custom trigger function, but that would be really cumbersome (you'd need an event listener for the event attached to the element and then have your condition inside it, times 2 for the other pattern).

Any chance you could implement this? :D

**Comment by justintaddei** [comment]
Using dynamic directive arguments yields a fairly clean result:

```vue
<template>
  <div>
    <CustomElement
      v-haptic:[statePattern]
    />
  </div>
</template>

<script>
export default {
  data() {
    return {
      isDisabled: false,
    };
  },
  computed: {
    statePattern() {
      return this.isDisabled ? "error" : "default";
    },
  },
};
</script>
```

What is your opinion on this?

**Comment by Chaphasilor** [comment]
Damn, yeah I totally did not think of that xD

That should work just fine!
