### ISSUE TITLE
Haptics triggered unwantedly while scrolling due to pointerdown

### ISSUE THREAD

**Issue by justintaddei** [justintaddei/vue-haptic#4]
> There may be a way I can use `pointercancel` detect when the event triggered while scrolling. I've been experimenting with that already for `v-wave`. If I find a solution I'll port that over here as well!

That sounds good. `click` is a bad fix, really (although it *should* be good), so fixing the unwanted scroll trigger on your end would be better for now 😅

_Originally posted by @Chaphasilor in https://github.com/justintaddei/vue-haptic/issues/2#issuecomment-713111823_

**Comment by justintaddei** [comment]
@Chaphasilor vue-haptic@1.2.0 introduces the `cancellationPeriod ` option. Everything should just work out-of-the-box after you update. If the delay is too long or too short for your liking, it can be adjusted with the aforementioned option.

**Comment by Chaphasilor** [comment]
More delays :/

But still, thanks for this!

As a heads-up, I noticed that the delay is significantly longer than specified when there's a compute-intensive operation running (i.e. v-shared-element cloning elements).  
Can you maybe make these operations asynchronous somehow, so they don't interfere with each other? Maybe this would also help to fix the issues with the `click` trigger event?

**Comment by justintaddei** [comment]
> More delays :/

Yeah, I know lol. Unfortunately this is the only way (to my knowledge) of accomplishing this. I believe it's actually the same way native implementations works (I say that based on experimenting, I haven't seen the source code)



> I noticed that the delay is significantly longer than specified when there's a compute-intensive operation running


Hmm. I may be able you get around that by using the capturing phase of the events instead of the bubbling phase. I'll see what I can come up with.

**Comment by justintaddei** [comment]
I'm going to move that to a new issue
