### ISSUE TITLE
Computationally intensive route change delays haptic feedback

### ISSUE THREAD

**Issue by justintaddei** [justintaddei/vue-haptic#6]
> As a heads-up, I noticed that the delay is significantly longer than specified when there's a compute-intensive operation running (i.e. v-shared-element cloning elements).  
Can you maybe make these operations asynchronous somehow, so they don't interfere with each other? Maybe this would also help to fix the issues with the `click` trigger event?

> _Originally posted by @Chaphasilor in https://github.com/justintaddei/vue-haptic/issues/4#issuecomment-717236234_

**Potential solution:**   
Using an event's capturing phase instead of bubbling to fake the haptic trigger having a higher priority.

**Comment by Chaphasilor** [comment]
Isn't there another way instead of 'faking'?
Isn't javascript able to use multiple threads when dealing with async functions?

**Comment by justintaddei** [comment]
Nope. Async is basically the same as the `defer` attribute on a script tag (except, you know, for code execution).

Essentially it just postpones the async part of the code until the main thread becomes idle (not to be confused with `requestIdleCallback` which waits for the user to be idle). So async is "out of sync" but it's not in parallel like a web worker would be.

The reason I'm thinking about using the capturing phase is that it will be fired before all other (non capturing) events. That's because it starts at the document root and works its way to the event target (opposite of bubbling phase).

![js-event-capture-bubble.png](https://user-images.githubusercontent.com/16705594/97332439-71bf3380-1848-11eb-9b1a-20a3f5fce2eb.png)

**Comment by Chaphasilor** [comment]
Huh. That's a pity. I was hoping this might also fix performance issues from v-shared-element 😅 

If you could experiement with using the capturing phase that would be awesome, after all, haptics should be as responsive as possible! 😉

**Comment by justintaddei** [comment]
So, after some experimentation, I realized that using the capturing phase is not a viable option. The reason being that vue-haptic uses `setTimeout` to facilitate the `cancellationPeriod`, resulting in the haptics being async and thus only happen _after_ the capturing and bubbling phases finish (so using a capturing event makes no difference).

After looking further into the issue, I don't see a way to mitigate this from within this project. I believe only the solution is to delay the computationally intensive task until after the haptics have fired, or find a way to reduce the intensiveness of the task if possible.

**Comment by Chaphasilor** [comment]
So basically add a delay to the `@click` event so that the route change only happens once the haptic has fired, right?

Thanks for looking into this again! :D

**Comment by justintaddei** [comment]
Unfortunately, yes. 

What I'm thinking is something like this:
```html
<button v-haptic @click="goTo('/')">Home</button>
```

```js
methods: {
    goTo(path) {
        setTimeout(() => {
            this.$router.push(path)
        }, 76) // 76 because the default delay for vue-haptic is 75.
    }
}
```

**Comment by justintaddei** [comment]
If I remember correctly, the "computationally intensive task" is, in your case, `v-shared-element`? If so, the v3 release provides some performance improvements and some ways to reduce the amount of work done per-navigation.

I wrote a small guide about dealing with that on the new example page for v-shared-element:  
https://justintaddei.github.io/v-shared-element/examples/dynamic-lists

**Comment by justintaddei** [comment]
I'm going close this issue since I don't see any practical way of resolving it, as of yet.

If I come up with any other ideas I'll reopen it.
